steps:
- id: 'p4-gpi-app-dev'
  name: '${_BUILD_NAMESPACE}/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'GIT_REF=${_GIT_REF}'
    - '--build-arg'
    - 'COMPOSER=${_COMPOSER}'
    - '--build-arg'
    - 'GITHUB_OAUTH_TOKEN=${_GITHUB_OAUTH_TOKEN}'
    - '--tag=${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app-dev:${_BRANCH_NAME}'
    - '--tag=${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app-dev:${_SHORT_SHA}'
    - '--tag=${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app-dev:${_BUILD_NUM}'
    - './app/${PROJECT_ID}/${_BUILD_ENVIRONMENT}/p4-gpi-app-dev'

images:
  - ${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app-dev:${_BRANCH_NAME}
  - ${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app-dev:${_SHORT_SHA}
  - ${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app-dev:${_BUILD_NUM}
