steps:
- id: 'configure-p4-gpi-app'
  name: 'ubuntu'
  dir: './environments/stage/p4-gpi-app'
  args:
    - '/bin/sed'
    - '-i'
    - '-r'
    - '-e'
    - 's;FROM.*;FROM ${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-onbuild:latest;g'
    - 'Dockerfile'

- id: 'p4-gpi-app'
  name: '${_BUILD_NAMESPACE}/cloud-builders/docker'
  args:
    - 'build'
    - '--build-arg'
    - 'GIT_REF=master'
    - '--build-arg'
    - 'GITHUB_OAUTH_TOKEN=${_GITHUB_OAUTH_TOKEN}'
    - '--tag=${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app:${_BUILD_TAG}'
    - '--tag=${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app:${_BUILD_NUM}'
    - '--tag=${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app:latest'
    - './environments/stage/p4-gpi-app'
  waitFor:
    - 'configure-p4-gpi-app'

images:
  - ${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app:${_BUILD_TAG}
  - ${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app:${_BUILD_NUM}
  - ${_BUILD_NAMESPACE}/${PROJECT_ID}/p4-gpi-app:latest
