defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
  docker:
    - image: gcr.io/planet-4-151612/circleci-base:latest
  working_directory:  /home/circleci/app

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Configure gcloud
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
      - run:
          name: Configure cloudbuild substitutions
          command: |
            # Rewrite cloudbuild variables
            SUBSTITUTIONS=(
              "_BUILD_NUM=${CIRCLE_BUILD_NUM}"
              "_BUILD_NAMESPACE=${BUILD_NAMESPACE:-'gcr.io'}" \
              "_BUILD_TAG=${BUILD_TAG:-${CIRCLE_TAG:-${CIRCLE_BRANCH}}}" \
              "_GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}" \
              "_SHORT_SHA=$(git rev-parse --short HEAD)" \
            )

            SUBSTITUTIONS_PROCESSOR="$(printf "%s," "${SUBSTITUTIONS[@]}")"
            SUBSTITUTIONS_STRING="${SUBSTITUTIONS_PROCESSOR%,}"
            export SUBSTITUTIONS_STRING

      - run:
          name: Building platform containers on gcr.io
          command: |
            # Submit dev build
            time ${HOME}/google-cloud-sdk/bin/gcloud container builds submit \
              cloudbuild-dev.yaml \
              --verbosity=${VERBOSITY:-'warning'} \
              --timeout=${BUILD_TIMEOUT:-'10m'} \
              --config cloudbuild-${BUILD_ENVIRONMENT:-'dev'}.yaml \
              --substitutions ${SUBSTITUTIONS_STRING}

  test:
    <<: *defaults
    steps:
      - run:
          name: Placeholder
          command: |
            echo "Branch: ${CIRCLE_BRANCH}"
            echo "Build:  ${CIRCLE_BUILD_NUM}"
            echo "Tag:    ${CIRCLE_TAG}"
            echo "No tests implemented yet"

  deploy:
    <<: *defaults
    steps:

      - run:
          name: Placeholder
          command: |
            echo "Branch: ${CIRCLE_BRANCH}"
            echo "Build:  ${CIRCLE_BUILD_NUM}"
            echo "Tag:    ${CIRCLE_TAG}"
            echo "Deploy not yet implemented"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      # Only run deploy job for tagged releases, any branch
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
