defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
    INFRA_VERSION: v0.7.1
    CONTAINER_PREFIX: planet4-base
    BUILD_FLAGS: -r
  docker:
    - image: gcr.io/planet-4-151612/p4-builder:v0.7.1
  working_directory:  /home/circleci/

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - setup_remote_docker

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh
            mkdir -p /tmp/workspace/var
            echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num

      - run:
          name: Build
          working_directory: /home/circleci
          command: |
            make

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

  # test:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: Placeholder
  #         command: |
  #           echo "Branch: ${CIRCLE_BRANCH}"
  #           echo "Build:  ${CIRCLE_BUILD_NUM}"
  #           echo "Tag:    ${CIRCLE_TAG}"
  #           echo "No tests implemented yet"

  deploy-develop:
    <<: *defaults
    steps:
      # - checkout
      #
      # - setup_remote_docker
      #

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure
          command: |
            ${HOME}/scripts/activate-gcloud-account.sh

      - run:
          name: Deploy new containers
          environment:
            APP_HOSTPATH: ""
            NEWRELIC_APPNAME: P4 Base Development
          command: |
            PHP_IMAGE=$(cat /tmp/workspace/var/circle-build-num) \
            OPENRESTY_IMAGE=$(cat /tmp/workspace/var/circle-build-num) \
            make deploy


workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/

      - deploy-develop:
          context: p4-base
          requires:
            - build
          filters:
            branches:
              only: develop

      # - test:
      #     requires:
      #       - build
      #     filters:
      #       tags:
      #         only: /.*/
      # Only run deploy job for tagged releases on master

      - hold-production:
          type: approval
          filters:
            tags:
              only: /v.*/
          requires:
            - build

      - deploy-production:
          context: org-global
          requires:
            - hold-production
          filters:
            tags:
              only: /v.*/
